live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]


[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 1.0

[font]
size = 12.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS Nerd Font Mono" 
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono" 
style = "Bold"

[colors.primary]
background = '#000000'


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true
